### ISSUE TITLE
Unhandled promise rejection on events

### ISSUE THREAD

**Issue by Xstoudi** [adonisjs/events#13]
## Package version
5.0.5 and previous

## Node.js and npm version
Warning before Node.js 15.0.0
Error since Node.js 15.0.0

NPM 7

## Sample Code (to reproduce the issue)
Create a Listener that throws.
```ts
export default class BoomListener {
  public async handleBoom() {
    throw new Error('boom');
  }
}
```

Register it in `start/events.ts`
```ts
Event.on('i-boom-ur-app', 'BoomListener.handleBoom');
```

Emit an event since anywhere:
```ts
Event.emit('i-boom-ur-app')
```

Previous Node.js 15, the app just throw a warning.
Since Node.js 15, the app crashes.

**Comment by thetutlage** [comment]
Isn't it same with the Node.js default event emitter too?

```ts
import { EventEmitter } from 'events'

const emitter = new EventEmitter()

emitter.on('foo', async () => {
  throw new Error('what???')
})

emitter.emit('foo', {})

```

**Comment by Xstoudi** [comment]
Yes it is, but Node.js expect a callback function in the event emitter, not a Promise.

Again, as I already said to Romain in private message, the problem is not a Node/Emiterry. It's Adonis that has to choose someting.

Here, we all know that we can't avoid errors in event handlers.
The only question that matter on that problem is "who should handle that error?"
- Should we monkey patch to catch errors globally?
- Should be `.catch` on each `Event.emit`?
- Add a global try-catch in each event handler?
- Or Adonis should handle it for us?

I personally think that the scope where `Event.emit` is called shouldn't even be aware of the result emission and that the execution flow of the previously mentionned scope musn't be interrupted by a throwing event.

**Comment by Xstoudi** [comment]
Tbh, by only returning a Promise, Adonis seems to says "hey ya, you have to handle `.catch` on your `Event.emit`". Is it on purpose or simply something that wasn't really though about?

**Comment by thetutlage** [comment]
I don't get the concern here. The same issue with the Node.js event emitter too. 

- Should I wrap every `Event.emit` inside a try/catch?
- Should I stick an `process.on('unhandledRejection')` handler?

> Tbh, by only returning a Promise, Adonis seems to says "hey ya, you have to handle .catch on your Event.emit".

When you call `Event.emit` on the native event emitter of Node.js. It literally run all the event listeners right away. So isn't that equivalent of asking to wrap each `Event.emit` inside `try/catch` as well?

**Comment by Xstoudi** [comment]
Again, I never talked about Node.js EventEmitter. I'm talking of the general developer experience of Adonis.
I don't think Events should be able to lead to an unresponsed request if we don't take care of it.

When an Event is emitted, the event (thus the error that can be raised in the event handler) should only be the event handler concern, not the emitter scope concern anymore.

Just to be sure to understand exactly what you expect from a proper event, I'll ask you a question:  What is the difference between emitting and event and directly calling the handler function, multiple listeners appart?

**Comment by thetutlage** [comment]
What you expect should happen. If you can suggest a proper well thought API, I am more than happy to look into it

**Comment by thetutlage** [comment]
Closing since not actionable
