### ISSUE TITLE
APIs to wait for event listeners to finish

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/events#21]
## Why this feature is required (specific use-cases will be appreciated)?
Within a test, if one wants to assert for actions performed inside an event listener, then cannot do that reliably, since events are async in nature. 

For example: The `UsersController.store` method fires an event after the user is created. That event performs an action, and I want to assert that in my code that action was executed successfully.

```ts
test('create user', ({ client }) => {
  await client.post('users').json({})

  // Here assert if action within event listener was successful.
  // However, I do not know when that listener gets executed.
})
```

## Have you tried any other work arounds?
The workaround is to wrap the assert code inside a `setTimeout` or `process.nextTick`. But, that is merely a hack and will cause some flakiness. 

## Are you willing to work on it with little guidance?
We need first class support to monitor events and run code after the all the listeners for a specific/all events have been executed successfully.

**Comment by RomainLanz** [comment]
I am not sure this is should be added to the framework.
In my opinion, an event is "fire and forget", you may not even have a listener for that event.

If you want to assert that the code was executed, it should not be inside an event handler but a direct call from your controller.
Using something like the action pattern may fix this issue.

**Comment by thetutlage** [comment]
I think its quite common to have business logic within event listeners. For example: Notify a new user has been created.

Now, I want to make sure that I have a listener in place that sends an email after a new user is created. How should I test that?

**Comment by RomainLanz** [comment]
Oh shoot, I haven't seen this was for testing and not for production code 😅

**Comment by albertovaccarella** [comment]
@thetutlage I see this feature request was abandoned, what's your recommended way of testing business logic inside event listeners in Adonis v6? Some sort of sleep during an e2e test? Or maybe separately, by unit testing the listener method(s) and unit testing that the right event is emitted with the right payload?

**Comment by thetutlage** [comment]
@albertovaccarella Yes, exactly as you mentioned.

The business logic is part of an Event listener that you can test separately and during other tests, you can fake the events and check if they were emitted with the right data or not. https://docs.adonisjs.com/guides/digging-deeper/emitter#faking-specific-events
