### ISSUE TITLE
Support emittery.emitSerial 

### ISSUE THREAD

**Issue by shiny** [adonisjs/events#22]
## Why this feature is required (specific use-cases will be appreciated)?

[emittery.emitSerial(eventName, data?)](https://github.com/sindresorhus/emittery#emitserialeventname-data)

> This can be useful if your events depend on each other. Although ideally they should not. Prefer emit() whenever possible.
If any of the listeners throw/reject, the returned promise will be rejected with the error and the remaining listeners will not be called.

In some cases we need guarantee the order of listeners, this API is quite usefull.

## Have you tried any other work arounds?
the other ways are not elegance as events

**Comment by thetutlage** [comment]
Added in https://github.com/adonisjs/events/commit/1e6ab2b1cd7197277e709679b0c85e0001fe6576. 

But this will be available with v6 release of `@adonisjs/core`
